<?php

namespace app\modules\admin\controllers;

use app\modules\admin\models\BlogCategory;

class CategoriesController extends AbstractCRUDController
{

    protected $modelClass = BlogCategory::class;
    public function actionIndex()
    {
       return parent::actionIndex();
    }
    public function actionView($id)
    {
        return parent::actionView($id);
    }
    public function actionCreate()
    {
        return parent::actionCreate(); // TODO: Change the autogenerated stub
    }
    public function actionUpdate($id)
    {
        return parent::actionUpdate($id); // TODO: Change the autogenerated stub
    }
}
